# Generated by Django 2.1.4 on 2019-12-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_f', models.ImageField(upload_to='../images')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
